name: Build

on:
  push:
    branches: [ main ]

jobs:
  lint:
    if: github.event_name == 'push'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          runtime: node@lts
          cache: true

      - name: 🔎 Lint
        run: node --run lint:eslint && node --run lint:stylelint

  test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          runtime: node@lts
          cache: true

      # - name: 🧪 Run test suite
      # run: pnpm test

      - name: 🧪 Test types
        run: node --run test:types

  build:
    needs: [lint, test]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout 🛎️
        uses: actions/checkout@v7
      - uses: pnpm/setup@v2
        with:
          runtime: node@lts
          cache: true
      
      - name: Build 🏗️
        run: node --run generate

      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: .output/public
